# Generated by Django 5.2.7 on 2025-10-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="№")),
                (
                    "delivery_number",
                    models.CharField(max_length=255, verbose_name="Номер поставки"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Предмет")),
                (
                    "nomenclature_code",
                    models.CharField(max_length=255, verbose_name="Код номенклатуры"),
                ),
                ("brand", models.CharField(max_length=255, verbose_name="Бренд")),
                (
                    "supplier_article",
                    models.CharField(max_length=255, verbose_name="Артикул поставщика"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("size", models.CharField(max_length=100, verbose_name="Размер")),
                ("barcode", models.CharField(max_length=255, verbose_name="Баркод")),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "payment_basis",
                    models.CharField(
                        max_length=255, verbose_name="Обоснование для оплаты"
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(verbose_name="Дата заказа покупателем"),
                ),
                ("sale_date", models.DateTimeField(verbose_name="Дата продажи")),
                ("quantity", models.IntegerField(verbose_name="Кол-во")),
                (
                    "retail_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена розничная"
                    ),
                ),
                (
                    "wb_sold_product",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Вайлдберриз реализовал Товар (Пр)",
                    ),
                ),
                (
                    "agreed_product_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Согласованный продуктовый дисконт, %",
                    ),
                ),
                (
                    "promo_code_percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Промокод %"
                    ),
                ),
                (
                    "total_agreed_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Итоговая согласованная скидка",
                    ),
                ),
                (
                    "retail_price_with_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Цена розничная с учетом согласованной скидки",
                    ),
                ),
                (
                    "kvv_reduction_rating",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Размер снижения кВВ из-за рейтинга, %",
                    ),
                ),
                (
                    "kvv_reduction_promotion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Размер снижения кВВ из-за акции, %",
                    ),
                ),
                (
                    "spp_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Скидка постоянного Покупателя (СПП)",
                    ),
                ),
                (
                    "kvv_size",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Размер кВВ, %"
                    ),
                ),
                (
                    "kvv_base_without_vat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Размер кВВ без НДС, % Базовый",
                    ),
                ),
                (
                    "kvv_final_without_vat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Итоговый кВВ без НДС, %",
                    ),
                ),
                (
                    "reward_before_services",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Вознаграждение с продаж до вычета услуг поверенного, без НДС",
                    ),
                ),
                (
                    "compensation_pickup_return",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Возмещение за выдачу и возврат товаров на ПВЗ",
                    ),
                ),
                (
                    "acquiring_commission",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Эквайринг/Комиссии за организацию платежей",
                    ),
                ),
                (
                    "acquiring_commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Размер комиссии за эквайринг/Комиссии за организацию платежей, %",
                    ),
                ),
                (
                    "acquiring_payment_type",
                    models.CharField(
                        max_length=255,
                        verbose_name="Тип платежа за Эквайринг/Комиссии за организацию платежей",
                    ),
                ),
                (
                    "wb_reward",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Вознаграждение Вайлдберриз (ВВ), без НДС",
                    ),
                ),
                (
                    "vat_wb_reward",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="НДС с Вознаграждения Вайлдберриз",
                    ),
                ),
                (
                    "payment_to_seller",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="К перечислению Продавцу за реализованный Товар",
                    ),
                ),
                (
                    "delivery_count",
                    models.IntegerField(verbose_name="Количество доставок"),
                ),
                (
                    "return_count",
                    models.IntegerField(verbose_name="Количество возврата"),
                ),
                (
                    "delivery_services",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Услуги по доставке товара покупателю",
                    ),
                ),
                (
                    "fixation_start_date",
                    models.DateTimeField(verbose_name="Дата начала действия фиксации"),
                ),
                (
                    "fixation_end_date",
                    models.DateTimeField(verbose_name="Дата конца действия фиксации"),
                ),
                (
                    "paid_delivery_flag",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Признак услуги платной доставки",
                    ),
                ),
                (
                    "total_fines",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Общая сумма штрафов",
                    ),
                ),
                (
                    "additional_payments",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Доплаты"
                    ),
                ),
                (
                    "logistics_types",
                    models.CharField(
                        max_length=255, verbose_name="Виды логистики, штрафов и доплат"
                    ),
                ),
                (
                    "mp_sticker",
                    models.CharField(max_length=255, verbose_name="Стикер МП"),
                ),
                (
                    "acquirer_bank",
                    models.CharField(
                        max_length=255, verbose_name="Наименование банка-эквайера"
                    ),
                ),
                (
                    "office_number",
                    models.CharField(max_length=255, verbose_name="Номер офиса"),
                ),
                (
                    "delivery_office",
                    models.CharField(
                        max_length=255, verbose_name="Наименование офиса доставки"
                    ),
                ),
                (
                    "partner_inn",
                    models.CharField(max_length=255, verbose_name="ИНН партнера"),
                ),
                ("partner", models.CharField(max_length=255, verbose_name="Партнер")),
                ("warehouse", models.CharField(max_length=255, verbose_name="Склад")),
                ("country", models.CharField(max_length=255, verbose_name="Страна")),
                (
                    "box_type",
                    models.CharField(max_length=255, verbose_name="Тип коробов"),
                ),
                (
                    "customs_declaration",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Номер таможенной декларации",
                    ),
                ),
                (
                    "assembly_task",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Номер сборочного задания",
                    ),
                ),
                (
                    "marking_code",
                    models.CharField(max_length=255, verbose_name="Код маркировки"),
                ),
                ("sku", models.CharField(max_length=255, verbose_name="ШК")),
                ("srid", models.CharField(max_length=255, verbose_name="Srid")),
                (
                    "transport_compensation",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Возмещение издержек по перевозке/по складским операциям с товаром",
                    ),
                ),
                (
                    "transport_organizer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Организатор перевозки",
                    ),
                ),
                (
                    "storage",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Хранение"
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Удержания"
                    ),
                ),
                (
                    "paid_reception",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Платная приемка"
                    ),
                ),
                ("chrt_id", models.CharField(max_length=255, verbose_name="chrtId")),
                (
                    "warehouse_coefficient",
                    models.CharField(
                        max_length=255,
                        verbose_name="Фиксированный коэффициент склада по поставке",
                    ),
                ),
            ],
            options={
                "verbose_name": "Финансовый отчет",
                "verbose_name_plural": "Финансовые отчеты",
            },
        ),
        migrations.CreateModel(
            name="PurchasePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(verbose_name="Позиция")),
                ("purchases", models.IntegerField(verbose_name="Выкупы")),
                (
                    "initial_position",
                    models.IntegerField(verbose_name="Изначальная позиция"),
                ),
                ("total_orders", models.IntegerField(verbose_name="Всего заказов")),
            ],
            options={
                "verbose_name": "План по выкупам",
                "verbose_name_plural": "Планы по выкупам",
            },
        ),
        migrations.CreateModel(
            name="SummaryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_minus_returns_count",
                    models.IntegerField(verbose_name="Продаж за вычетом возвратов, шт"),
                ),
                (
                    "purchase_percentage",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="Процент выкупа"
                    ),
                ),
                (
                    "average_check_after_spp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Средний чек для покупателя после СПП",
                    ),
                ),
                (
                    "commission_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Комиссия на 1 продажу, руб",
                    ),
                ),
                (
                    "logistics_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Логистика на 1 продажу, руб",
                    ),
                ),
                (
                    "storage_per_unit",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        verbose_name="Хранение на 1 продажу, руб",
                    ),
                ),
                (
                    "sold_goods_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Себестоимость проданных товаров",
                    ),
                ),
                (
                    "average_cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Средняя себестоимость 1 продажи, руб",
                    ),
                ),
                (
                    "average_margin_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Средняя маржа с 1 продажи, руб",
                    ),
                ),
                (
                    "margin_without_ads",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Маржа за период БЕЗ учета рекламы, руб",
                    ),
                ),
                (
                    "margin_per_unit_without_ads",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Средняя маржа с 1 продажи, руб (без рекламы)",
                    ),
                ),
                (
                    "margin_after_all_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Маржа за период после всех расходов МП и налогов, руб",
                    ),
                ),
                (
                    "total_commission",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Комиссия"
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="Комиссия %"
                    ),
                ),
                (
                    "total_logistics",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Логистика"
                    ),
                ),
                (
                    "logistics_percent",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="Логистика %"
                    ),
                ),
                (
                    "total_storage",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Хранение"
                    ),
                ),
                (
                    "storage_percent",
                    models.DecimalField(
                        decimal_places=6, max_digits=8, verbose_name="Хранение %"
                    ),
                ),
                (
                    "additional_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Доплаты",
                    ),
                ),
                (
                    "fines",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Штрафы",
                    ),
                ),
                (
                    "paid_reception",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Платная приемка",
                    ),
                ),
                (
                    "advertising_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Удержания (реклама)",
                    ),
                ),
                (
                    "advertising_percent",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Удержания (реклама) %",
                    ),
                ),
                (
                    "transit_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Удержания (транзит и др)",
                    ),
                ),
                (
                    "acquiring",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Эквайринг"
                    ),
                ),
                (
                    "defect_compensation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Компенсация брака",
                    ),
                ),
                (
                    "substitution_compensation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Компенсация подмен (продажи)",
                    ),
                ),
                (
                    "margin_percent_before_spp",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Маржинальность от продаж до СПП, %",
                    ),
                ),
                (
                    "margin_percent_with_spp",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Маржинальность от продаж с СПП, %",
                    ),
                ),
                (
                    "margin_percent_after_commission",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Маржинальность от продаж за вычетом комиссии, %",
                    ),
                ),
                (
                    "sales_before_spp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Продажи по ценам до СПП",
                    ),
                ),
                (
                    "sales_with_spp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Продажи по ценам с СПП",
                    ),
                ),
                (
                    "sales_minus_commission",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Продажи за вычетом комиссии",
                    ),
                ),
                (
                    "payment_to_account",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="К перечислению на р/с",
                    ),
                ),
                (
                    "tax_6_percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Налог 6%"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Сводные данные",
                "verbose_name_plural": "Сводные данные",
            },
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255, verbose_name="Бренд")),
                ("subject", models.CharField(max_length=255, verbose_name="Предмет")),
                (
                    "size_code",
                    models.CharField(
                        max_length=255, verbose_name="Код размера (chrt_id)"
                    ),
                ),
                (
                    "supplier_article",
                    models.CharField(max_length=255, verbose_name="Артикул продавца"),
                ),
                (
                    "wb_article",
                    models.CharField(max_length=255, verbose_name="Артикул WB"),
                ),
                ("size", models.CharField(max_length=100, verbose_name="Размер")),
                ("barcode", models.CharField(max_length=255, verbose_name="Баркод")),
                (
                    "equipment",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Комплектация"
                    ),
                ),
                (
                    "composition",
                    models.TextField(blank=True, null=True, verbose_name="Состав"),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Себестоимость"
                    ),
                ),
            ],
            options={
                "verbose_name": "Номенклатура",
                "verbose_name_plural": "Номенклатуры",
                "unique_together": {("brand", "supplier_article", "size")},
            },
        ),
        migrations.CreateModel(
            name="SalesAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255, verbose_name="Бренд")),
                ("subject", models.CharField(max_length=255, verbose_name="Предмет")),
                ("article", models.CharField(max_length=255, verbose_name="Артикул")),
                ("size", models.CharField(max_length=100, verbose_name="Размер")),
                ("barcode", models.CharField(max_length=255, verbose_name="Баркод")),
                (
                    "in_transit_to_client",
                    models.IntegerField(default=0, verbose_name="В пути до клиента"),
                ),
                (
                    "in_transit_from_client",
                    models.IntegerField(default=0, verbose_name="В пути от клиента"),
                ),
                (
                    "in_warehouses",
                    models.IntegerField(default=0, verbose_name="На складах"),
                ),
                (
                    "total_stock_wb",
                    models.IntegerField(default=0, verbose_name="ИТОГО остаток на ВБ"),
                ),
                (
                    "turnover_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Оборачиваемость, дней"
                    ),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="Заказы, шт")),
                ("rejections", models.IntegerField(default=0, verbose_name="Отказы")),
                ("sales", models.IntegerField(default=0, verbose_name="Продажи, шт")),
                (
                    "returns",
                    models.IntegerField(default=0, verbose_name="Возвраты, шт"),
                ),
                (
                    "sales_minus_returns",
                    models.IntegerField(
                        default=0, verbose_name="Продажи минус возвраты"
                    ),
                ),
                (
                    "purchase_percentage",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="Процент выкупа",
                    ),
                ),
                (
                    "supplier_return",
                    models.IntegerField(default=0, verbose_name="Возврат, шт"),
                ),
                (
                    "logistics_for_returns",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Логистика за возвраты",
                    ),
                ),
                (
                    "sales_before_spp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Продажи по ценам до СПП",
                    ),
                ),
                (
                    "sales_with_spp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Продажи по ценам с СПП",
                    ),
                ),
                (
                    "sales_minus_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Продажи за вычетом комиссии",
                    ),
                ),
                (
                    "sales_minus_commission_no_returns",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Продажи за вычетом комиссии (без учета возвратов)",
                    ),
                ),
                (
                    "return_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Возвраты",
                    ),
                ),
                (
                    "sales_minus_returns_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Продажи минус возвраты",
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Комиссия, руб",
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="Комиссия %",
                    ),
                ),
                (
                    "logistics",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Логистика",
                    ),
                ),
                (
                    "logistics_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Логистика на 1 продажу",
                    ),
                ),
                (
                    "acquiring",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Эквайринг",
                    ),
                ),
                (
                    "fine",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Штраф"
                    ),
                ),
                (
                    "additional_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Доплаты",
                    ),
                ),
                (
                    "substitution_compensation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Компенсация подмен",
                    ),
                ),
                (
                    "defect_compensation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Возмещение брака",
                    ),
                ),
                (
                    "average_check",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Средний чек",
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Себестомость 1 шт",
                    ),
                ),
                (
                    "sold_goods_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Себестоимость проданного товара",
                    ),
                ),
                (
                    "margin_before_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Маржа до налогов",
                    ),
                ),
                (
                    "tax_6_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Налог 6%",
                    ),
                ),
                (
                    "margin_after_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Маржа после налогов, руб",
                    ),
                ),
                (
                    "margin_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Маржа на 1 продажу, руб",
                    ),
                ),
                (
                    "margin_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="Маржинальность, %",
                    ),
                ),
                (
                    "roi_from_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="ROI от себестоимости, %",
                    ),
                ),
                (
                    "gmroi",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="GMROI, %",
                    ),
                ),
                (
                    "revenue_share",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="Доля от общей выручки, %",
                    ),
                ),
                (
                    "margin_share",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        verbose_name="Доля от общей маржи, %",
                    ),
                ),
                (
                    "abc_by_cost",
                    models.CharField(
                        default="", max_length=1, verbose_name="По себестоимости"
                    ),
                ),
                (
                    "abc_by_price",
                    models.CharField(
                        default="",
                        max_length=1,
                        verbose_name="По цене за вычетом комиссии",
                    ),
                ),
                (
                    "abc_by_margin",
                    models.CharField(
                        default="", max_length=1, verbose_name="По средней марже"
                    ),
                ),
                (
                    "money_in_goods",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Деньги в товаре",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анализ продаж",
                "verbose_name_plural": "Анализ продаж",
                "unique_together": {("brand", "article", "size")},
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255, verbose_name="Бренд")),
                ("subject", models.CharField(max_length=255, verbose_name="Предмет")),
                (
                    "supplier_article",
                    models.CharField(max_length=255, verbose_name="Артикул продавца"),
                ),
                (
                    "item_size",
                    models.CharField(max_length=100, verbose_name="Размер вещи"),
                ),
                (
                    "in_transit_to_client",
                    models.IntegerField(verbose_name="В пути до клиента"),
                ),
                (
                    "in_transit_from_client",
                    models.IntegerField(verbose_name="В пути от клиента"),
                ),
                (
                    "total_in_warehouses",
                    models.IntegerField(verbose_name="Итого по складам"),
                ),
            ],
            options={
                "verbose_name": "Остаток на складе",
                "verbose_name_plural": "Остатки на складах",
                "unique_together": {("brand", "supplier_article", "item_size")},
            },
        ),
    ]
