# Generated by Django 5.2.7 on 2025-10-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialreport",
            name="acquirer_bank",
            field=models.CharField(
                default="", max_length=255, verbose_name="Наименование банка-эквайера"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="acquiring_commission",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Эквайринг/Комиссии за организацию платежей",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="acquiring_commission_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Размер комиссии за эквайринг/Комиссии за организацию платежей, %",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="acquiring_payment_type",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="Тип платежа за Эквайринг/Комиссии за организацию платежей",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="additional_payments",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Доплаты"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="agreed_product_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Согласованный продуктовый дисконт, %",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="box_type",
            field=models.CharField(
                default="", max_length=255, verbose_name="Тип коробов"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="chrt_id",
            field=models.CharField(default="", max_length=255, verbose_name="chrtId"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="compensation_pickup_return",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Возмещение за выдачу и возврат товаров на ПВЗ",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="country",
            field=models.CharField(default="", max_length=255, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="deductions",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Удержания"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="delivery_count",
            field=models.IntegerField(default=0, verbose_name="Количество доставок"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="delivery_office",
            field=models.CharField(
                default="", max_length=255, verbose_name="Наименование офиса доставки"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="delivery_services",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Услуги по доставке товара покупателю",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="fixation_end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата конца действия фиксации"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="fixation_start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата начала действия фиксации"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="kvv_base_without_vat",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Размер кВВ без НДС, % Базовый",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="kvv_final_without_vat",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Итоговый кВВ без НДС, %",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="kvv_reduction_promotion",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Размер снижения кВВ из-за акции, %",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="kvv_reduction_rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Размер снижения кВВ из-за рейтинга, %",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="kvv_size",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Размер кВВ, %"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="logistics_types",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="Виды логистики, штрафов и доплат",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="marking_code",
            field=models.CharField(
                default="", max_length=255, verbose_name="Код маркировки"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="mp_sticker",
            field=models.CharField(
                default="", max_length=255, verbose_name="Стикер МП"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="office_number",
            field=models.CharField(
                default="", max_length=255, verbose_name="Номер офиса"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="paid_reception",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Платная приемка",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="partner",
            field=models.CharField(default="", max_length=255, verbose_name="Партнер"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="partner_inn",
            field=models.CharField(
                default="", max_length=255, verbose_name="ИНН партнера"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="payment_to_seller",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="К перечислению Продавцу за реализованный Товар",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="promo_code_percent",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Промокод %"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="retail_price_with_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Цена розничная с учетом согласованной скидки",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="return_count",
            field=models.IntegerField(default=0, verbose_name="Количество возврата"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="reward_before_services",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Вознаграждение с продаж до вычета услуг поверенного, без НДС",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="sku",
            field=models.CharField(default="", max_length=255, verbose_name="ШК"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="spp_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Скидка постоянного Покупателя (СПП)",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="srid",
            field=models.CharField(default="", max_length=255, verbose_name="Srid"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="storage",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Хранение"
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="total_agreed_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Итоговая согласованная скидка",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="total_fines",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Общая сумма штрафов",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="transport_compensation",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Возмещение издержек по перевозке/по складским операциям с товаром",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="vat_wb_reward",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="НДС с Вознаграждения Вайлдберриз",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="warehouse",
            field=models.CharField(default="", max_length=255, verbose_name="Склад"),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="warehouse_coefficient",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="Фиксированный коэффициент склада по поставке",
            ),
        ),
        migrations.AlterField(
            model_name="financialreport",
            name="wb_reward",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Вознаграждение Вайлдберриз (ВВ), без НДС",
            ),
        ),
    ]
